// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo8y4KTBQVEa94o_tfc2bpmW9pr4hk8fY',
    appId: '1:29310863866:web:2c708763b679be38753c43',
    messagingSenderId: '29310863866',
    projectId: 'authentication-cdc88',
    authDomain: 'authentication-cdc88.firebaseapp.com',
    storageBucket: 'authentication-cdc88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyi-hvm4c-AeuJugY2cPXjyJq_GLRyrp8',
    appId: '1:29310863866:android:21888b89a2738294753c43',
    messagingSenderId: '29310863866',
    projectId: 'authentication-cdc88',
    storageBucket: 'authentication-cdc88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnhPJJuKwgm1jZvT-5LsCl0R7BvBafvMA',
    appId: '1:29310863866:ios:d0bfc08ab45e1e09753c43',
    messagingSenderId: '29310863866',
    projectId: 'authentication-cdc88',
    storageBucket: 'authentication-cdc88.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnhPJJuKwgm1jZvT-5LsCl0R7BvBafvMA',
    appId: '1:29310863866:ios:d0bfc08ab45e1e09753c43',
    messagingSenderId: '29310863866',
    projectId: 'authentication-cdc88',
    storageBucket: 'authentication-cdc88.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo8y4KTBQVEa94o_tfc2bpmW9pr4hk8fY',
    appId: '1:29310863866:web:1dbe5c9ad8d7f775753c43',
    messagingSenderId: '29310863866',
    projectId: 'authentication-cdc88',
    authDomain: 'authentication-cdc88.firebaseapp.com',
    storageBucket: 'authentication-cdc88.firebasestorage.app',
  );
}
